# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RXDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'RxSwift-SwiftyJSON', '~> 1.1'
   pod 'RxSwiftExt', '~> 2.1.0'
   pod 'RxSwift', '~> 3.2.0'
   pod 'SnapKit', '~> 3.2.0'
   pod 'Alamofire', '~> 4.4.0'
   pod 'AlamofireImage', '~> 3.1'
   pod 'Kingfisher', '~> 3.5.1'
  # Pods for RXDemo

end
